version: 2

sources:
  - name: de_journey_dw
    database: de-journey-492321
    schema: de_journey_dw
    tables:
      - name: sales
        config:
          loaded_at_field: loaded_at  
          freshness:
            warn_after: {count: 24, period: hour}
            error_after: {count: 48, period: hour}